version: "3.8"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    # image: skvggor/pankkivahva
    environment:
      - DB_HOSTNAME=pankkivahva
      - PORT=3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

  api02:
    <<: *api
    network_mode: host
    environment:
      - DB_HOSTNAME=pankkivahva
      - PORT=3001

  load-balancer:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: pankkivahva
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=pankkivahva
      - PORT=5432
    volumes:
      - ./migrations/0001_create_tables.sql:/docker-entrypoint-initdb.d/0001_create_tables.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"
